/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 monke.glb --transform -t 
Files: monke.glb [69.68KB] > /Users/ethanhoward/dev/webxr-test/src/models/monke-transformed.glb [6.42KB] (91%)
*/

import { Mesh } from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Suzanne: Mesh
  }
  materials: {}
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/monke-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.material} />
    </group>
  )
}

useGLTF.preload('/monke-transformed.glb')
