/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 src/models/uclan_sm.glb --transform -t -r public 
Files: src/models/uclan_sm.glb [2.06MB] > /Users/ethanhoward/dev/webxr-test/uclan_sm-transformed.glb [486.04KB] (76%)
*/

import { Mesh, MeshBasicMaterial } from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0007: Mesh
    Mesh_0007_1: Mesh
    Mesh_0007_2: Mesh
    Mesh_0007_3: Mesh
    Mesh_0007_4: Mesh
    Mesh_0007_5: Mesh
    Mesh_0007_6: Mesh
    Mesh_0007_7: Mesh
    Mesh_0007_8: Mesh
    Mesh_0007_9: Mesh
    Mesh_0007_10: Mesh
    Mesh_0007_11: Mesh
    Mesh_0007_12: Mesh
    Mesh_0007_13: Mesh
    Mesh_0007_14: Mesh
  }
  materials: {
    ['Material_0.007']: MeshBasicMaterial
    Material_0: MeshBasicMaterial
    Material_1: MeshBasicMaterial
    ['Material_0.001']: MeshBasicMaterial
    ['Material_1.001']: MeshBasicMaterial
    ['Material_0.002']: MeshBasicMaterial
    ['Material_1.002']: MeshBasicMaterial
    ['Material_0.003']: MeshBasicMaterial
    ['Material_1.003']: MeshBasicMaterial
    ['Material_0.004']: MeshBasicMaterial
    ['Material_1.004']: MeshBasicMaterial
    ['Material_0.005']: MeshBasicMaterial
    ['Material_1.005']: MeshBasicMaterial
    ['Material_0.006']: MeshBasicMaterial
    ['Material_1.006']: MeshBasicMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/../uclan_sm-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0007.geometry} material={materials['Material_0.007']} />
      <mesh geometry={nodes.Mesh_0007_1.geometry} material={materials.Material_0} />
      <mesh geometry={nodes.Mesh_0007_2.geometry} material={materials.Material_1} />
      <mesh geometry={nodes.Mesh_0007_3.geometry} material={materials['Material_0.001']} />
      <mesh geometry={nodes.Mesh_0007_4.geometry} material={materials['Material_1.001']} />
      <mesh geometry={nodes.Mesh_0007_5.geometry} material={materials['Material_0.002']} />
      <mesh geometry={nodes.Mesh_0007_6.geometry} material={materials['Material_1.002']} />
      <mesh geometry={nodes.Mesh_0007_7.geometry} material={materials['Material_0.003']} />
      <mesh geometry={nodes.Mesh_0007_8.geometry} material={materials['Material_1.003']} />
      <mesh geometry={nodes.Mesh_0007_9.geometry} material={materials['Material_0.004']} />
      <mesh geometry={nodes.Mesh_0007_10.geometry} material={materials['Material_1.004']} />
      <mesh geometry={nodes.Mesh_0007_11.geometry} material={materials['Material_0.005']} />
      <mesh geometry={nodes.Mesh_0007_12.geometry} material={materials['Material_1.005']} />
      <mesh geometry={nodes.Mesh_0007_13.geometry} material={materials['Material_0.006']} />
      <mesh geometry={nodes.Mesh_0007_14.geometry} material={materials['Material_1.006']} />
    </group>
  )
}

useGLTF.preload('/../uclan_sm-transformed.glb')
