/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 src/models/uclan_lg.glb --transform -t -r public 
Files: src/models/uclan_lg.glb [93.14MB] > /Users/ethanhoward/dev/webxr-test/uclan_lg-transformed.glb [15.58MB] (83%)
*/

import { Mesh, MeshBasicMaterial } from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0487: Mesh
    Mesh_0487_1: Mesh
    Mesh_0487_2: Mesh
    Mesh_0487_3: Mesh
    Mesh_0487_4: Mesh
    Mesh_0487_5: Mesh
    Mesh_0487_6: Mesh
    Mesh_0487_7: Mesh
    Mesh_0487_8: Mesh
    Mesh_0487_9: Mesh
    Mesh_0487_10: Mesh
    Mesh_0487_11: Mesh
    Mesh_0487_12: Mesh
    Mesh_0487_13: Mesh
    Mesh_0487_14: Mesh
    Mesh_0487_15: Mesh
    Mesh_0487_16: Mesh
    Mesh_0487_17: Mesh
    Mesh_0487_18: Mesh
    Mesh_0487_19: Mesh
    Mesh_0487_20: Mesh
    Mesh_0487_21: Mesh
    Mesh_0487_22: Mesh
    Mesh_0487_23: Mesh
    Mesh_0487_24: Mesh
    Mesh_0487_25: Mesh
    Mesh_0487_26: Mesh
    Mesh_0487_27: Mesh
    Mesh_0487_28: Mesh
    Mesh_0487_29: Mesh
    Mesh_0487_30: Mesh
    Mesh_0487_31: Mesh
    Mesh_0487_32: Mesh
    Mesh_0487_33: Mesh
    Mesh_0487_34: Mesh
    Mesh_0487_35: Mesh
    Mesh_0487_36: Mesh
    Mesh_0487_37: Mesh
    Mesh_0487_38: Mesh
    Mesh_0487_39: Mesh
    Mesh_0487_40: Mesh
    Mesh_0487_41: Mesh
    Mesh_0487_42: Mesh
    Mesh_0487_43: Mesh
    Mesh_0487_44: Mesh
    Mesh_0487_45: Mesh
    Mesh_0487_46: Mesh
    Mesh_0487_47: Mesh
    Mesh_0487_48: Mesh
    Mesh_0487_49: Mesh
    Mesh_0487_50: Mesh
    Mesh_0487_51: Mesh
    Mesh_0487_52: Mesh
    Mesh_0487_53: Mesh
    Mesh_0487_54: Mesh
    Mesh_0487_55: Mesh
    Mesh_0487_56: Mesh
    Mesh_0487_57: Mesh
    Mesh_0487_58: Mesh
    Mesh_0487_59: Mesh
    Mesh_0487_60: Mesh
    Mesh_0487_61: Mesh
    Mesh_0487_62: Mesh
    Mesh_0487_63: Mesh
    Mesh_0487_64: Mesh
    Mesh_0487_65: Mesh
    Mesh_0487_66: Mesh
    Mesh_0487_67: Mesh
    Mesh_0487_68: Mesh
    Mesh_0487_69: Mesh
    Mesh_0487_70: Mesh
    Mesh_0487_71: Mesh
    Mesh_0487_72: Mesh
    Mesh_0487_73: Mesh
    Mesh_0487_74: Mesh
    Mesh_0487_75: Mesh
    Mesh_0487_76: Mesh
    Mesh_0487_77: Mesh
    Mesh_0487_78: Mesh
    Mesh_0487_79: Mesh
    Mesh_0487_80: Mesh
    Mesh_0487_81: Mesh
    Mesh_0487_82: Mesh
    Mesh_0487_83: Mesh
    Mesh_0487_84: Mesh
    Mesh_0487_85: Mesh
    Mesh_0487_86: Mesh
    Mesh_0487_87: Mesh
    Mesh_0487_88: Mesh
    Mesh_0487_89: Mesh
    Mesh_0487_90: Mesh
    Mesh_0487_91: Mesh
    Mesh_0487_92: Mesh
    Mesh_0487_93: Mesh
    Mesh_0487_94: Mesh
    Mesh_0487_95: Mesh
    Mesh_0487_96: Mesh
    Mesh_0487_97: Mesh
    Mesh_0487_98: Mesh
    Mesh_0487_99: Mesh
    Mesh_0487_100: Mesh
    Mesh_0487_101: Mesh
    Mesh_0487_102: Mesh
    Mesh_0487_103: Mesh
    Mesh_0487_104: Mesh
    Mesh_0487_105: Mesh
    Mesh_0487_106: Mesh
    Mesh_0487_107: Mesh
    Mesh_0487_108: Mesh
    Mesh_0487_109: Mesh
    Mesh_0487_110: Mesh
    Mesh_0487_111: Mesh
    Mesh_0487_112: Mesh
    Mesh_0487_113: Mesh
    Mesh_0487_114: Mesh
    Mesh_0487_115: Mesh
    Mesh_0487_116: Mesh
    Mesh_0487_117: Mesh
    Mesh_0487_118: Mesh
    Mesh_0487_119: Mesh
    Mesh_0487_120: Mesh
    Mesh_0487_121: Mesh
    Mesh_0487_122: Mesh
    Mesh_0487_123: Mesh
    Mesh_0487_124: Mesh
    Mesh_0487_125: Mesh
    Mesh_0487_126: Mesh
    Mesh_0487_127: Mesh
    Mesh_0487_128: Mesh
    Mesh_0487_129: Mesh
    Mesh_0487_130: Mesh
    Mesh_0487_131: Mesh
    Mesh_0487_132: Mesh
    Mesh_0487_133: Mesh
    Mesh_0487_134: Mesh
    Mesh_0487_135: Mesh
    Mesh_0487_136: Mesh
    Mesh_0487_137: Mesh
    Mesh_0487_138: Mesh
    Mesh_0487_139: Mesh
    Mesh_0487_140: Mesh
    Mesh_0487_141: Mesh
    Mesh_0487_142: Mesh
    Mesh_0487_143: Mesh
    Mesh_0487_144: Mesh
    Mesh_0487_145: Mesh
    Mesh_0487_146: Mesh
    Mesh_0487_147: Mesh
    Mesh_0487_148: Mesh
    Mesh_0487_149: Mesh
    Mesh_0487_150: Mesh
    Mesh_0487_151: Mesh
    Mesh_0487_152: Mesh
    Mesh_0487_153: Mesh
    Mesh_0487_154: Mesh
    Mesh_0487_155: Mesh
    Mesh_0487_156: Mesh
    Mesh_0487_157: Mesh
    Mesh_0487_158: Mesh
    Mesh_0487_159: Mesh
    Mesh_0487_160: Mesh
    Mesh_0487_161: Mesh
    Mesh_0487_162: Mesh
    Mesh_0487_163: Mesh
    Mesh_0487_164: Mesh
    Mesh_0487_165: Mesh
    Mesh_0487_166: Mesh
    Mesh_0487_167: Mesh
    Mesh_0487_168: Mesh
    Mesh_0487_169: Mesh
    Mesh_0487_170: Mesh
    Mesh_0487_171: Mesh
    Mesh_0487_172: Mesh
    Mesh_0487_173: Mesh
    Mesh_0487_174: Mesh
    Mesh_0487_175: Mesh
    Mesh_0487_176: Mesh
    Mesh_0487_177: Mesh
    Mesh_0487_178: Mesh
    Mesh_0487_179: Mesh
    Mesh_0487_180: Mesh
    Mesh_0487_181: Mesh
    Mesh_0487_182: Mesh
    Mesh_0487_183: Mesh
    Mesh_0487_184: Mesh
    Mesh_0487_185: Mesh
    Mesh_0487_186: Mesh
    Mesh_0487_187: Mesh
    Mesh_0487_188: Mesh
    Mesh_0487_189: Mesh
    Mesh_0487_190: Mesh
    Mesh_0487_191: Mesh
    Mesh_0487_192: Mesh
    Mesh_0487_193: Mesh
    Mesh_0487_194: Mesh
    Mesh_0487_195: Mesh
    Mesh_0487_196: Mesh
    Mesh_0487_197: Mesh
    Mesh_0487_198: Mesh
    Mesh_0487_199: Mesh
    Mesh_0487_200: Mesh
    Mesh_0487_201: Mesh
    Mesh_0487_202: Mesh
    Mesh_0487_203: Mesh
    Mesh_0487_204: Mesh
    Mesh_0487_205: Mesh
    Mesh_0487_206: Mesh
    Mesh_0487_207: Mesh
    Mesh_0487_208: Mesh
    Mesh_0487_209: Mesh
    Mesh_0487_210: Mesh
    Mesh_0487_211: Mesh
    Mesh_0487_212: Mesh
    Mesh_0487_213: Mesh
    Mesh_0487_214: Mesh
    Mesh_0487_215: Mesh
    Mesh_0487_216: Mesh
    Mesh_0487_217: Mesh
    Mesh_0487_218: Mesh
    Mesh_0487_219: Mesh
    Mesh_0487_220: Mesh
    Mesh_0487_221: Mesh
    Mesh_0487_222: Mesh
    Mesh_0487_223: Mesh
    Mesh_0487_224: Mesh
    Mesh_0487_225: Mesh
    Mesh_0487_226: Mesh
    Mesh_0487_227: Mesh
    Mesh_0487_228: Mesh
    Mesh_0487_229: Mesh
    Mesh_0487_230: Mesh
    Mesh_0487_231: Mesh
    Mesh_0487_232: Mesh
    Mesh_0487_233: Mesh
    Mesh_0487_234: Mesh
    Mesh_0487_235: Mesh
    Mesh_0487_236: Mesh
    Mesh_0487_237: Mesh
    Mesh_0487_238: Mesh
    Mesh_0487_239: Mesh
    Mesh_0487_240: Mesh
    Mesh_0487_241: Mesh
    Mesh_0487_242: Mesh
    Mesh_0487_243: Mesh
    Mesh_0487_244: Mesh
    Mesh_0487_245: Mesh
    Mesh_0487_246: Mesh
    Mesh_0487_247: Mesh
    Mesh_0487_248: Mesh
    Mesh_0487_249: Mesh
    Mesh_0487_250: Mesh
    Mesh_0487_251: Mesh
    Mesh_0487_252: Mesh
    Mesh_0487_253: Mesh
    Mesh_0487_254: Mesh
    Mesh_0487_255: Mesh
    Mesh_0487_256: Mesh
    Mesh_0487_257: Mesh
    Mesh_0487_258: Mesh
    Mesh_0487_259: Mesh
    Mesh_0487_260: Mesh
    Mesh_0487_261: Mesh
    Mesh_0487_262: Mesh
    Mesh_0487_263: Mesh
    Mesh_0487_264: Mesh
    Mesh_0487_265: Mesh
    Mesh_0487_266: Mesh
    Mesh_0487_267: Mesh
    Mesh_0487_268: Mesh
    Mesh_0487_269: Mesh
    Mesh_0487_270: Mesh
    Mesh_0487_271: Mesh
    Mesh_0487_272: Mesh
    Mesh_0487_273: Mesh
    Mesh_0487_274: Mesh
    Mesh_0487_275: Mesh
    Mesh_0487_276: Mesh
    Mesh_0487_277: Mesh
    Mesh_0487_278: Mesh
    Mesh_0487_279: Mesh
    Mesh_0487_280: Mesh
    Mesh_0487_281: Mesh
    Mesh_0487_282: Mesh
    Mesh_0487_283: Mesh
    Mesh_0487_284: Mesh
    Mesh_0487_285: Mesh
    Mesh_0487_286: Mesh
    Mesh_0487_287: Mesh
    Mesh_0487_288: Mesh
    Mesh_0487_289: Mesh
    Mesh_0487_290: Mesh
    Mesh_0487_291: Mesh
    Mesh_0487_292: Mesh
    Mesh_0487_293: Mesh
    Mesh_0487_294: Mesh
    Mesh_0487_295: Mesh
    Mesh_0487_296: Mesh
    Mesh_0487_297: Mesh
    Mesh_0487_298: Mesh
    Mesh_0487_299: Mesh
    Mesh_0487_300: Mesh
    Mesh_0487_301: Mesh
    Mesh_0487_302: Mesh
    Mesh_0487_303: Mesh
    Mesh_0487_304: Mesh
    Mesh_0487_305: Mesh
    Mesh_0487_306: Mesh
    Mesh_0487_307: Mesh
    Mesh_0487_308: Mesh
    Mesh_0487_309: Mesh
    Mesh_0487_310: Mesh
    Mesh_0487_311: Mesh
    Mesh_0487_312: Mesh
    Mesh_0487_313: Mesh
    Mesh_0487_314: Mesh
    Mesh_0487_315: Mesh
    Mesh_0487_316: Mesh
    Mesh_0487_317: Mesh
    Mesh_0487_318: Mesh
    Mesh_0487_319: Mesh
    Mesh_0487_320: Mesh
    Mesh_0487_321: Mesh
    Mesh_0487_322: Mesh
    Mesh_0487_323: Mesh
    Mesh_0487_324: Mesh
    Mesh_0487_325: Mesh
    Mesh_0487_326: Mesh
    Mesh_0487_327: Mesh
    Mesh_0487_328: Mesh
    Mesh_0487_329: Mesh
    Mesh_0487_330: Mesh
    Mesh_0487_331: Mesh
    Mesh_0487_332: Mesh
    Mesh_0487_333: Mesh
    Mesh_0487_334: Mesh
    Mesh_0487_335: Mesh
    Mesh_0487_336: Mesh
    Mesh_0487_337: Mesh
    Mesh_0487_338: Mesh
    Mesh_0487_339: Mesh
    Mesh_0487_340: Mesh
    Mesh_0487_341: Mesh
    Mesh_0487_342: Mesh
    Mesh_0487_343: Mesh
    Mesh_0487_344: Mesh
    Mesh_0487_345: Mesh
    Mesh_0487_346: Mesh
    Mesh_0487_347: Mesh
    Mesh_0487_348: Mesh
    Mesh_0487_349: Mesh
    Mesh_0487_350: Mesh
    Mesh_0487_351: Mesh
    Mesh_0487_352: Mesh
    Mesh_0487_353: Mesh
    Mesh_0487_354: Mesh
    Mesh_0487_355: Mesh
    Mesh_0487_356: Mesh
    Mesh_0487_357: Mesh
    Mesh_0487_358: Mesh
    Mesh_0487_359: Mesh
    Mesh_0487_360: Mesh
    Mesh_0487_361: Mesh
    Mesh_0487_362: Mesh
    Mesh_0487_363: Mesh
    Mesh_0487_364: Mesh
    Mesh_0487_365: Mesh
    Mesh_0487_366: Mesh
    Mesh_0487_367: Mesh
    Mesh_0487_368: Mesh
    Mesh_0487_369: Mesh
    Mesh_0487_370: Mesh
    Mesh_0487_371: Mesh
    Mesh_0487_372: Mesh
    Mesh_0487_373: Mesh
    Mesh_0487_374: Mesh
    Mesh_0487_375: Mesh
    Mesh_0487_376: Mesh
    Mesh_0487_377: Mesh
    Mesh_0487_378: Mesh
    Mesh_0487_379: Mesh
    Mesh_0487_380: Mesh
    Mesh_0487_381: Mesh
    Mesh_0487_382: Mesh
    Mesh_0487_383: Mesh
    Mesh_0487_384: Mesh
    Mesh_0487_385: Mesh
    Mesh_0487_386: Mesh
    Mesh_0487_387: Mesh
    Mesh_0487_388: Mesh
    Mesh_0487_389: Mesh
    Mesh_0487_390: Mesh
    Mesh_0487_391: Mesh
    Mesh_0487_392: Mesh
    Mesh_0487_393: Mesh
    Mesh_0487_394: Mesh
    Mesh_0487_395: Mesh
    Mesh_0487_396: Mesh
    Mesh_0487_397: Mesh
    Mesh_0487_398: Mesh
    Mesh_0487_399: Mesh
    Mesh_0487_400: Mesh
    Mesh_0487_401: Mesh
    Mesh_0487_402: Mesh
    Mesh_0487_403: Mesh
    Mesh_0487_404: Mesh
    Mesh_0487_405: Mesh
    Mesh_0487_406: Mesh
    Mesh_0487_407: Mesh
    Mesh_0487_408: Mesh
    Mesh_0487_409: Mesh
    Mesh_0487_410: Mesh
    Mesh_0487_411: Mesh
    Mesh_0487_412: Mesh
    Mesh_0487_413: Mesh
    Mesh_0487_414: Mesh
    Mesh_0487_415: Mesh
    Mesh_0487_416: Mesh
    Mesh_0487_417: Mesh
    Mesh_0487_418: Mesh
    Mesh_0487_419: Mesh
    Mesh_0487_420: Mesh
    Mesh_0487_421: Mesh
    Mesh_0487_422: Mesh
    Mesh_0487_423: Mesh
    Mesh_0487_424: Mesh
    Mesh_0487_425: Mesh
    Mesh_0487_426: Mesh
    Mesh_0487_427: Mesh
    Mesh_0487_428: Mesh
    Mesh_0487_429: Mesh
    Mesh_0487_430: Mesh
    Mesh_0487_431: Mesh
    Mesh_0487_432: Mesh
    Mesh_0487_433: Mesh
    Mesh_0487_434: Mesh
    Mesh_0487_435: Mesh
    Mesh_0487_436: Mesh
    Mesh_0487_437: Mesh
    Mesh_0487_438: Mesh
    Mesh_0487_439: Mesh
    Mesh_0487_440: Mesh
    Mesh_0487_441: Mesh
    Mesh_0487_442: Mesh
    Mesh_0487_443: Mesh
    Mesh_0487_444: Mesh
    Mesh_0487_445: Mesh
    Mesh_0487_446: Mesh
    Mesh_0487_447: Mesh
    Mesh_0487_448: Mesh
    Mesh_0487_449: Mesh
    Mesh_0487_450: Mesh
    Mesh_0487_451: Mesh
    Mesh_0487_452: Mesh
    Mesh_0487_453: Mesh
    Mesh_0487_454: Mesh
    Mesh_0487_455: Mesh
    Mesh_0487_456: Mesh
    Mesh_0487_457: Mesh
    Mesh_0487_458: Mesh
    Mesh_0487_459: Mesh
    Mesh_0487_460: Mesh
    Mesh_0487_461: Mesh
    Mesh_0487_462: Mesh
    Mesh_0487_463: Mesh
    Mesh_0487_464: Mesh
    Mesh_0487_465: Mesh
    Mesh_0487_466: Mesh
    Mesh_0487_467: Mesh
    Mesh_0487_468: Mesh
    Mesh_0487_469: Mesh
    Mesh_0487_470: Mesh
    Mesh_0487_471: Mesh
    Mesh_0487_472: Mesh
    Mesh_0487_473: Mesh
  }
  materials: {
    ['Material_0.487']: MeshBasicMaterial
    ['Material_0.010']: MeshBasicMaterial
    ['Material_0.011']: MeshBasicMaterial
    ['Material_0.014']: MeshBasicMaterial
    ['Material_0.021']: MeshBasicMaterial
    ['Material_0.023']: MeshBasicMaterial
    ['Material_1.009']: MeshBasicMaterial
    ['Material_0.027']: MeshBasicMaterial
    ['Material_0.028']: MeshBasicMaterial
    ['Material_0.029']: MeshBasicMaterial
    ['Material_1.011']: MeshBasicMaterial
    ['Material_0.030']: MeshBasicMaterial
    ['Material_1.012']: MeshBasicMaterial
    ['Material_0.031']: MeshBasicMaterial
    ['Material_1.013']: MeshBasicMaterial
    ['Material_0.032']: MeshBasicMaterial
    ['Material_1.014']: MeshBasicMaterial
    ['Material_0.033']: MeshBasicMaterial
    ['Material_1.015']: MeshBasicMaterial
    Material_2: MeshBasicMaterial
    ['Material_0.034']: MeshBasicMaterial
    ['Material_1.016']: MeshBasicMaterial
    ['Material_0.035']: MeshBasicMaterial
    ['Material_1.017']: MeshBasicMaterial
    ['Material_0.036']: MeshBasicMaterial
    ['Material_1.018']: MeshBasicMaterial
    ['Material_2.001']: MeshBasicMaterial
    ['Material_0.037']: MeshBasicMaterial
    ['Material_0.038']: MeshBasicMaterial
    ['Material_0.039']: MeshBasicMaterial
    ['Material_1.019']: MeshBasicMaterial
    ['Material_0.040']: MeshBasicMaterial
    ['Material_1.020']: MeshBasicMaterial
    ['Material_0.041']: MeshBasicMaterial
    ['Material_0.042']: MeshBasicMaterial
    ['Material_1.021']: MeshBasicMaterial
    ['Material_0.043']: MeshBasicMaterial
    ['Material_1.022']: MeshBasicMaterial
    ['Material_0.044']: MeshBasicMaterial
    ['Material_0.045']: MeshBasicMaterial
    ['Material_0.046']: MeshBasicMaterial
    ['Material_1.023']: MeshBasicMaterial
    ['Material_0.047']: MeshBasicMaterial
    ['Material_0.051']: MeshBasicMaterial
    ['Material_1.025']: MeshBasicMaterial
    ['Material_0.053']: MeshBasicMaterial
    ['Material_1.027']: MeshBasicMaterial
    ['Material_0.054']: MeshBasicMaterial
    ['Material_0.056']: MeshBasicMaterial
    ['Material_1.028']: MeshBasicMaterial
    ['Material_0.057']: MeshBasicMaterial
    ['Material_0.060']: MeshBasicMaterial
    ['Material_0.064']: MeshBasicMaterial
    ['Material_1.031']: MeshBasicMaterial
    ['Material_0.065']: MeshBasicMaterial
    ['Material_1.032']: MeshBasicMaterial
    ['Material_0.066']: MeshBasicMaterial
    ['Material_1.033']: MeshBasicMaterial
    ['Material_0.067']: MeshBasicMaterial
    ['Material_1.034']: MeshBasicMaterial
    ['Material_0.068']: MeshBasicMaterial
    ['Material_1.035']: MeshBasicMaterial
    ['Material_0.069']: MeshBasicMaterial
    ['Material_1.036']: MeshBasicMaterial
    ['Material_0.070']: MeshBasicMaterial
    ['Material_1.037']: MeshBasicMaterial
    ['Material_0.071']: MeshBasicMaterial
    ['Material_1.038']: MeshBasicMaterial
    ['Material_0.072']: MeshBasicMaterial
    ['Material_1.039']: MeshBasicMaterial
    ['Material_0.073']: MeshBasicMaterial
    ['Material_1.040']: MeshBasicMaterial
    ['Material_0.074']: MeshBasicMaterial
    ['Material_1.041']: MeshBasicMaterial
    ['Material_0.075']: MeshBasicMaterial
    ['Material_1.042']: MeshBasicMaterial
    ['Material_0.076']: MeshBasicMaterial
    ['Material_1.043']: MeshBasicMaterial
    ['Material_0.077']: MeshBasicMaterial
    ['Material_1.044']: MeshBasicMaterial
    ['Material_0.078']: MeshBasicMaterial
    ['Material_1.045']: MeshBasicMaterial
    ['Material_0.079']: MeshBasicMaterial
    ['Material_1.046']: MeshBasicMaterial
    ['Material_0.080']: MeshBasicMaterial
    ['Material_1.047']: MeshBasicMaterial
    ['Material_0.081']: MeshBasicMaterial
    ['Material_1.048']: MeshBasicMaterial
    ['Material_0.082']: MeshBasicMaterial
    ['Material_1.049']: MeshBasicMaterial
    ['Material_0.083']: MeshBasicMaterial
    ['Material_1.050']: MeshBasicMaterial
    ['Material_0.085']: MeshBasicMaterial
    ['Material_1.052']: MeshBasicMaterial
    ['Material_0.086']: MeshBasicMaterial
    ['Material_1.053']: MeshBasicMaterial
    ['Material_0.087']: MeshBasicMaterial
    ['Material_0.088']: MeshBasicMaterial
    ['Material_1.055']: MeshBasicMaterial
    ['Material_0.092']: MeshBasicMaterial
    ['Material_0.093']: MeshBasicMaterial
    ['Material_0.094']: MeshBasicMaterial
    ['Material_0.095']: MeshBasicMaterial
    ['Material_0.096']: MeshBasicMaterial
    ['Material_0.098']: MeshBasicMaterial
    ['Material_0.099']: MeshBasicMaterial
    ['Material_0.100']: MeshBasicMaterial
    ['Material_1.058']: MeshBasicMaterial
    ['Material_0.101']: MeshBasicMaterial
    ['Material_1.059']: MeshBasicMaterial
    ['Material_0.102']: MeshBasicMaterial
    ['Material_1.060']: MeshBasicMaterial
    ['Material_0.103']: MeshBasicMaterial
    ['Material_1.061']: MeshBasicMaterial
    ['Material_0.104']: MeshBasicMaterial
    ['Material_1.062']: MeshBasicMaterial
    ['Material_0.105']: MeshBasicMaterial
    ['Material_1.063']: MeshBasicMaterial
    ['Material_0.106']: MeshBasicMaterial
    ['Material_1.064']: MeshBasicMaterial
    ['Material_0.107']: MeshBasicMaterial
    ['Material_1.065']: MeshBasicMaterial
    ['Material_0.108']: MeshBasicMaterial
    ['Material_1.066']: MeshBasicMaterial
    ['Material_0.109']: MeshBasicMaterial
    ['Material_1.067']: MeshBasicMaterial
    ['Material_0.110']: MeshBasicMaterial
    ['Material_1.068']: MeshBasicMaterial
    ['Material_0.111']: MeshBasicMaterial
    ['Material_1.069']: MeshBasicMaterial
    ['Material_0.112']: MeshBasicMaterial
    ['Material_0.113']: MeshBasicMaterial
    ['Material_1.070']: MeshBasicMaterial
    ['Material_0.114']: MeshBasicMaterial
    ['Material_0.115']: MeshBasicMaterial
    ['Material_1.071']: MeshBasicMaterial
    ['Material_0.116']: MeshBasicMaterial
    ['Material_0.117']: MeshBasicMaterial
    ['Material_1.072']: MeshBasicMaterial
    ['Material_0.118']: MeshBasicMaterial
    ['Material_0.119']: MeshBasicMaterial
    ['Material_1.073']: MeshBasicMaterial
    ['Material_0.120']: MeshBasicMaterial
    ['Material_0.121']: MeshBasicMaterial
    ['Material_0.122']: MeshBasicMaterial
    ['Material_1.074']: MeshBasicMaterial
    ['Material_0.123']: MeshBasicMaterial
    ['Material_1.075']: MeshBasicMaterial
    ['Material_0.124']: MeshBasicMaterial
    ['Material_1.076']: MeshBasicMaterial
    ['Material_0.125']: MeshBasicMaterial
    ['Material_1.077']: MeshBasicMaterial
    ['Material_0.126']: MeshBasicMaterial
    ['Material_0.127']: MeshBasicMaterial
    ['Material_1.078']: MeshBasicMaterial
    ['Material_0.128']: MeshBasicMaterial
    ['Material_1.079']: MeshBasicMaterial
    ['Material_0.133']: MeshBasicMaterial
    ['Material_1.084']: MeshBasicMaterial
    ['Material_0.134']: MeshBasicMaterial
    ['Material_0.135']: MeshBasicMaterial
    ['Material_1.085']: MeshBasicMaterial
    ['Material_0.136']: MeshBasicMaterial
    ['Material_1.086']: MeshBasicMaterial
    ['Material_0.138']: MeshBasicMaterial
    ['Material_1.088']: MeshBasicMaterial
    ['Material_0.140']: MeshBasicMaterial
    ['Material_1.090']: MeshBasicMaterial
    ['Material_0.141']: MeshBasicMaterial
    ['Material_1.091']: MeshBasicMaterial
    ['Material_0.142']: MeshBasicMaterial
    ['Material_1.092']: MeshBasicMaterial
    ['Material_0.143']: MeshBasicMaterial
    ['Material_1.093']: MeshBasicMaterial
    ['Material_0.144']: MeshBasicMaterial
    ['Material_1.094']: MeshBasicMaterial
    ['Material_0.145']: MeshBasicMaterial
    ['Material_0.146']: MeshBasicMaterial
    ['Material_0.147']: MeshBasicMaterial
    ['Material_1.095']: MeshBasicMaterial
    ['Material_0.148']: MeshBasicMaterial
    ['Material_1.096']: MeshBasicMaterial
    ['Material_0.149']: MeshBasicMaterial
    ['Material_0.150']: MeshBasicMaterial
    ['Material_1.097']: MeshBasicMaterial
    ['Material_0.151']: MeshBasicMaterial
    ['Material_1.098']: MeshBasicMaterial
    ['Material_0.152']: MeshBasicMaterial
    ['Material_1.099']: MeshBasicMaterial
    ['Material_0.153']: MeshBasicMaterial
    ['Material_1.100']: MeshBasicMaterial
    ['Material_0.154']: MeshBasicMaterial
    ['Material_1.101']: MeshBasicMaterial
    ['Material_0.155']: MeshBasicMaterial
    ['Material_1.102']: MeshBasicMaterial
    ['Material_0.156']: MeshBasicMaterial
    ['Material_1.103']: MeshBasicMaterial
    ['Material_0.157']: MeshBasicMaterial
    ['Material_0.158']: MeshBasicMaterial
    ['Material_1.104']: MeshBasicMaterial
    ['Material_0.159']: MeshBasicMaterial
    ['Material_1.105']: MeshBasicMaterial
    ['Material_0.160']: MeshBasicMaterial
    ['Material_1.106']: MeshBasicMaterial
    ['Material_0.161']: MeshBasicMaterial
    ['Material_0.162']: MeshBasicMaterial
    ['Material_0.163']: MeshBasicMaterial
    ['Material_0.164']: MeshBasicMaterial
    ['Material_0.165']: MeshBasicMaterial
    ['Material_0.166']: MeshBasicMaterial
    ['Material_0.167']: MeshBasicMaterial
    ['Material_0.168']: MeshBasicMaterial
    ['Material_0.169']: MeshBasicMaterial
    ['Material_0.170']: MeshBasicMaterial
    ['Material_0.171']: MeshBasicMaterial
    ['Material_1.107']: MeshBasicMaterial
    ['Material_0.172']: MeshBasicMaterial
    ['Material_1.108']: MeshBasicMaterial
    ['Material_0.173']: MeshBasicMaterial
    ['Material_0.174']: MeshBasicMaterial
    ['Material_0.175']: MeshBasicMaterial
    ['Material_1.109']: MeshBasicMaterial
    ['Material_0.176']: MeshBasicMaterial
    ['Material_1.110']: MeshBasicMaterial
    ['Material_0.177']: MeshBasicMaterial
    ['Material_1.111']: MeshBasicMaterial
    ['Material_0.178']: MeshBasicMaterial
    ['Material_1.112']: MeshBasicMaterial
    ['Material_0.179']: MeshBasicMaterial
    ['Material_0.180']: MeshBasicMaterial
    ['Material_0.181']: MeshBasicMaterial
    ['Material_0.182']: MeshBasicMaterial
    ['Material_0.183']: MeshBasicMaterial
    ['Material_0.184']: MeshBasicMaterial
    ['Material_1.113']: MeshBasicMaterial
    ['Material_0.185']: MeshBasicMaterial
    ['Material_0.198']: MeshBasicMaterial
    ['Material_0.199']: MeshBasicMaterial
    ['Material_1.121']: MeshBasicMaterial
    ['Material_0.200']: MeshBasicMaterial
    ['Material_1.122']: MeshBasicMaterial
    ['Material_0.201']: MeshBasicMaterial
    ['Material_1.123']: MeshBasicMaterial
    ['Material_0.202']: MeshBasicMaterial
    ['Material_1.124']: MeshBasicMaterial
    ['Material_0.203']: MeshBasicMaterial
    ['Material_1.125']: MeshBasicMaterial
    ['Material_0.204']: MeshBasicMaterial
    ['Material_1.126']: MeshBasicMaterial
    ['Material_0.205']: MeshBasicMaterial
    ['Material_1.127']: MeshBasicMaterial
    ['Material_0.206']: MeshBasicMaterial
    ['Material_0.207']: MeshBasicMaterial
    ['Material_0.208']: MeshBasicMaterial
    ['Material_1.128']: MeshBasicMaterial
    ['Material_0.209']: MeshBasicMaterial
    ['Material_0.210']: MeshBasicMaterial
    ['Material_0.211']: MeshBasicMaterial
    ['Material_0.212']: MeshBasicMaterial
    ['Material_0.213']: MeshBasicMaterial
    ['Material_1.129']: MeshBasicMaterial
    ['Material_0.214']: MeshBasicMaterial
    ['Material_0.216']: MeshBasicMaterial
    ['Material_0.220']: MeshBasicMaterial
    ['Material_0.221']: MeshBasicMaterial
    ['Material_0.222']: MeshBasicMaterial
    ['Material_0.223']: MeshBasicMaterial
    ['Material_1.133']: MeshBasicMaterial
    ['Material_0.226']: MeshBasicMaterial
    ['Material_0.227']: MeshBasicMaterial
    ['Material_0.228']: MeshBasicMaterial
    ['Material_0.236']: MeshBasicMaterial
    ['Material_0.237']: MeshBasicMaterial
    ['Material_0.238']: MeshBasicMaterial
    ['Material_0.239']: MeshBasicMaterial
    ['Material_0.240']: MeshBasicMaterial
    ['Material_0.241']: MeshBasicMaterial
    ['Material_0.242']: MeshBasicMaterial
    ['Material_0.248']: MeshBasicMaterial
    ['Material_0.254']: MeshBasicMaterial
    ['Material_0.256']: MeshBasicMaterial
    ['Material_0.257']: MeshBasicMaterial
    ['Material_0.258']: MeshBasicMaterial
    ['Material_1.135']: MeshBasicMaterial
    ['Material_0.259']: MeshBasicMaterial
    ['Material_1.136']: MeshBasicMaterial
    ['Material_0.260']: MeshBasicMaterial
    ['Material_0.266']: MeshBasicMaterial
    ['Material_0.269']: MeshBasicMaterial
    ['Material_1.143']: MeshBasicMaterial
    ['Material_0.270']: MeshBasicMaterial
    ['Material_0.271']: MeshBasicMaterial
    ['Material_1.144']: MeshBasicMaterial
    ['Material_0.272']: MeshBasicMaterial
    ['Material_1.145']: MeshBasicMaterial
    ['Material_0.273']: MeshBasicMaterial
    ['Material_1.146']: MeshBasicMaterial
    ['Material_0.274']: MeshBasicMaterial
    ['Material_1.147']: MeshBasicMaterial
    ['Material_0.275']: MeshBasicMaterial
    ['Material_1.148']: MeshBasicMaterial
    ['Material_0.276']: MeshBasicMaterial
    ['Material_1.149']: MeshBasicMaterial
    ['Material_0.277']: MeshBasicMaterial
    ['Material_1.150']: MeshBasicMaterial
    ['Material_0.278']: MeshBasicMaterial
    ['Material_1.151']: MeshBasicMaterial
    ['Material_0.279']: MeshBasicMaterial
    ['Material_1.152']: MeshBasicMaterial
    ['Material_0.280']: MeshBasicMaterial
    ['Material_1.153']: MeshBasicMaterial
    ['Material_0.281']: MeshBasicMaterial
    ['Material_1.154']: MeshBasicMaterial
    ['Material_0.282']: MeshBasicMaterial
    ['Material_1.155']: MeshBasicMaterial
    ['Material_0.283']: MeshBasicMaterial
    ['Material_1.156']: MeshBasicMaterial
    ['Material_0.284']: MeshBasicMaterial
    ['Material_1.157']: MeshBasicMaterial
    ['Material_0.301']: MeshBasicMaterial
    ['Material_1.166']: MeshBasicMaterial
    ['Material_0.302']: MeshBasicMaterial
    ['Material_0.305']: MeshBasicMaterial
    ['Material_1.169']: MeshBasicMaterial
    ['Material_0.306']: MeshBasicMaterial
    ['Material_1.170']: MeshBasicMaterial
    ['Material_0.307']: MeshBasicMaterial
    ['Material_1.171']: MeshBasicMaterial
    ['Material_0.308']: MeshBasicMaterial
    ['Material_0.322']: MeshBasicMaterial
    ['Material_0.323']: MeshBasicMaterial
    ['Material_0.324']: MeshBasicMaterial
    ['Material_0.325']: MeshBasicMaterial
    ['Material_0.326']: MeshBasicMaterial
    ['Material_0.327']: MeshBasicMaterial
    ['Material_0.328']: MeshBasicMaterial
    ['Material_0.329']: MeshBasicMaterial
    ['Material_0.330']: MeshBasicMaterial
    ['Material_0.332']: MeshBasicMaterial
    ['Material_0.333']: MeshBasicMaterial
    ['Material_0.334']: MeshBasicMaterial
    ['Material_0.335']: MeshBasicMaterial
    ['Material_0.336']: MeshBasicMaterial
    ['Material_1.176']: MeshBasicMaterial
    ['Material_0.337']: MeshBasicMaterial
    ['Material_1.177']: MeshBasicMaterial
    ['Material_0.338']: MeshBasicMaterial
    ['Material_1.178']: MeshBasicMaterial
    ['Material_0.339']: MeshBasicMaterial
    ['Material_1.179']: MeshBasicMaterial
    ['Material_0.340']: MeshBasicMaterial
    ['Material_0.341']: MeshBasicMaterial
    ['Material_1.180']: MeshBasicMaterial
    ['Material_0.342']: MeshBasicMaterial
    ['Material_1.181']: MeshBasicMaterial
    ['Material_0.343']: MeshBasicMaterial
    ['Material_1.182']: MeshBasicMaterial
    ['Material_0.344']: MeshBasicMaterial
    ['Material_1.183']: MeshBasicMaterial
    ['Material_0.345']: MeshBasicMaterial
    ['Material_1.184']: MeshBasicMaterial
    ['Material_0.346']: MeshBasicMaterial
    ['Material_1.185']: MeshBasicMaterial
    ['Material_0.347']: MeshBasicMaterial
    ['Material_0.348']: MeshBasicMaterial
    ['Material_1.186']: MeshBasicMaterial
    ['Material_0.349']: MeshBasicMaterial
    ['Material_1.187']: MeshBasicMaterial
    ['Material_0.350']: MeshBasicMaterial
    ['Material_0.351']: MeshBasicMaterial
    ['Material_1.188']: MeshBasicMaterial
    ['Material_0.352']: MeshBasicMaterial
    ['Material_0.353']: MeshBasicMaterial
    ['Material_0.354']: MeshBasicMaterial
    ['Material_1.189']: MeshBasicMaterial
    ['Material_0.355']: MeshBasicMaterial
    ['Material_0.358']: MeshBasicMaterial
    ['Material_1.191']: MeshBasicMaterial
    ['Material_0.359']: MeshBasicMaterial
    ['Material_1.192']: MeshBasicMaterial
    ['Material_0.360']: MeshBasicMaterial
    ['Material_1.193']: MeshBasicMaterial
    ['Material_0.361']: MeshBasicMaterial
    ['Material_1.194']: MeshBasicMaterial
    ['Material_0.364']: MeshBasicMaterial
    ['Material_0.365']: MeshBasicMaterial
    ['Material_1.195']: MeshBasicMaterial
    ['Material_0.366']: MeshBasicMaterial
    ['Material_0.367']: MeshBasicMaterial
    ['Material_1.196']: MeshBasicMaterial
    ['Material_0.368']: MeshBasicMaterial
    ['Material_0.369']: MeshBasicMaterial
    ['Material_1.197']: MeshBasicMaterial
    ['Material_0.370']: MeshBasicMaterial
    ['Material_1.198']: MeshBasicMaterial
    ['Material_0.371']: MeshBasicMaterial
    ['Material_1.199']: MeshBasicMaterial
    ['Material_0.372']: MeshBasicMaterial
    ['Material_0.373']: MeshBasicMaterial
    ['Material_1.200']: MeshBasicMaterial
    ['Material_0.375']: MeshBasicMaterial
    ['Material_0.376']: MeshBasicMaterial
    ['Material_1.202']: MeshBasicMaterial
    ['Material_0.377']: MeshBasicMaterial
    ['Material_0.378']: MeshBasicMaterial
    ['Material_1.203']: MeshBasicMaterial
    ['Material_0.379']: MeshBasicMaterial
    ['Material_1.204']: MeshBasicMaterial
    ['Material_0.380']: MeshBasicMaterial
    ['Material_1.205']: MeshBasicMaterial
    ['Material_0.381']: MeshBasicMaterial
    ['Material_0.382']: MeshBasicMaterial
    ['Material_1.206']: MeshBasicMaterial
    ['Material_0.383']: MeshBasicMaterial
    ['Material_0.386']: MeshBasicMaterial
    ['Material_1.208']: MeshBasicMaterial
    ['Material_0.387']: MeshBasicMaterial
    ['Material_0.388']: MeshBasicMaterial
    ['Material_1.210']: MeshBasicMaterial
    ['Material_0.389']: MeshBasicMaterial
    ['Material_0.392']: MeshBasicMaterial
    ['Material_0.393']: MeshBasicMaterial
    ['Material_0.394']: MeshBasicMaterial
    ['Material_0.395']: MeshBasicMaterial
    ['Material_0.396']: MeshBasicMaterial
    ['Material_0.397']: MeshBasicMaterial
    ['Material_0.398']: MeshBasicMaterial
    ['Material_0.399']: MeshBasicMaterial
    ['Material_0.400']: MeshBasicMaterial
    ['Material_0.401']: MeshBasicMaterial
    ['Material_0.402']: MeshBasicMaterial
    ['Material_0.403']: MeshBasicMaterial
    ['Material_0.404']: MeshBasicMaterial
    ['Material_0.405']: MeshBasicMaterial
    ['Material_0.406']: MeshBasicMaterial
    ['Material_0.407']: MeshBasicMaterial
    ['Material_0.409']: MeshBasicMaterial
    ['Material_0.412']: MeshBasicMaterial
    ['Material_0.414']: MeshBasicMaterial
    ['Material_0.418']: MeshBasicMaterial
    ['Material_0.419']: MeshBasicMaterial
    ['Material_0.420']: MeshBasicMaterial
    ['Material_0.421']: MeshBasicMaterial
    ['Material_0.422']: MeshBasicMaterial
    ['Material_0.423']: MeshBasicMaterial
    ['Material_0.424']: MeshBasicMaterial
    ['Material_0.425']: MeshBasicMaterial
    ['Material_0.426']: MeshBasicMaterial
    ['Material_0.427']: MeshBasicMaterial
    ['Material_0.428']: MeshBasicMaterial
    ['Material_0.429']: MeshBasicMaterial
    ['Material_0.434']: MeshBasicMaterial
    ['Material_0.467']: MeshBasicMaterial
    ['Material_1.226']: MeshBasicMaterial
    ['Material_0.468']: MeshBasicMaterial
    ['Material_1.227']: MeshBasicMaterial
    ['Material_0.469']: MeshBasicMaterial
    ['Material_0.470']: MeshBasicMaterial
    ['Material_0.473']: MeshBasicMaterial
    ['Material_1.228']: MeshBasicMaterial
    ['Material_0.474']: MeshBasicMaterial
    ['Material_1.229']: MeshBasicMaterial
    ['Material_0.475']: MeshBasicMaterial
    ['Material_1.230']: MeshBasicMaterial
    ['Material_0.476']: MeshBasicMaterial
    ['Material_1.231']: MeshBasicMaterial
    ['Material_0.477']: MeshBasicMaterial
    ['Material_0.478']: MeshBasicMaterial
    ['Material_1.232']: MeshBasicMaterial
    ['Material_0.481']: MeshBasicMaterial
    ['Material_0.482']: MeshBasicMaterial
    ['Material_0.484']: MeshBasicMaterial
    ['Material_0.485']: MeshBasicMaterial
    ['Material_0.486']: MeshBasicMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/../uclan_lg-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0487.geometry} material={materials['Material_0.487']} />
      <mesh geometry={nodes.Mesh_0487_1.geometry} material={materials['Material_0.010']} />
      <mesh geometry={nodes.Mesh_0487_2.geometry} material={materials['Material_0.011']} />
      <mesh geometry={nodes.Mesh_0487_3.geometry} material={materials['Material_0.014']} />
      <mesh geometry={nodes.Mesh_0487_4.geometry} material={materials['Material_0.021']} />
      <mesh geometry={nodes.Mesh_0487_5.geometry} material={materials['Material_0.023']} />
      <mesh geometry={nodes.Mesh_0487_6.geometry} material={materials['Material_1.009']} />
      <mesh geometry={nodes.Mesh_0487_7.geometry} material={materials['Material_0.027']} />
      <mesh geometry={nodes.Mesh_0487_8.geometry} material={materials['Material_0.028']} />
      <mesh geometry={nodes.Mesh_0487_9.geometry} material={materials['Material_0.029']} />
      <mesh geometry={nodes.Mesh_0487_10.geometry} material={materials['Material_1.011']} />
      <mesh geometry={nodes.Mesh_0487_11.geometry} material={materials['Material_0.030']} />
      <mesh geometry={nodes.Mesh_0487_12.geometry} material={materials['Material_1.012']} />
      <mesh geometry={nodes.Mesh_0487_13.geometry} material={materials['Material_0.031']} />
      <mesh geometry={nodes.Mesh_0487_14.geometry} material={materials['Material_1.013']} />
      <mesh geometry={nodes.Mesh_0487_15.geometry} material={materials['Material_0.032']} />
      <mesh geometry={nodes.Mesh_0487_16.geometry} material={materials['Material_1.014']} />
      <mesh geometry={nodes.Mesh_0487_17.geometry} material={materials['Material_0.033']} />
      <mesh geometry={nodes.Mesh_0487_18.geometry} material={materials['Material_1.015']} />
      <mesh geometry={nodes.Mesh_0487_19.geometry} material={materials.Material_2} />
      <mesh geometry={nodes.Mesh_0487_20.geometry} material={materials['Material_0.034']} />
      <mesh geometry={nodes.Mesh_0487_21.geometry} material={materials['Material_1.016']} />
      <mesh geometry={nodes.Mesh_0487_22.geometry} material={materials['Material_0.035']} />
      <mesh geometry={nodes.Mesh_0487_23.geometry} material={materials['Material_1.017']} />
      <mesh geometry={nodes.Mesh_0487_24.geometry} material={materials['Material_0.036']} />
      <mesh geometry={nodes.Mesh_0487_25.geometry} material={materials['Material_1.018']} />
      <mesh geometry={nodes.Mesh_0487_26.geometry} material={materials['Material_2.001']} />
      <mesh geometry={nodes.Mesh_0487_27.geometry} material={materials['Material_0.037']} />
      <mesh geometry={nodes.Mesh_0487_28.geometry} material={materials['Material_0.038']} />
      <mesh geometry={nodes.Mesh_0487_29.geometry} material={materials['Material_0.039']} />
      <mesh geometry={nodes.Mesh_0487_30.geometry} material={materials['Material_1.019']} />
      <mesh geometry={nodes.Mesh_0487_31.geometry} material={materials['Material_0.040']} />
      <mesh geometry={nodes.Mesh_0487_32.geometry} material={materials['Material_1.020']} />
      <mesh geometry={nodes.Mesh_0487_33.geometry} material={materials['Material_0.041']} />
      <mesh geometry={nodes.Mesh_0487_34.geometry} material={materials['Material_0.042']} />
      <mesh geometry={nodes.Mesh_0487_35.geometry} material={materials['Material_1.021']} />
      <mesh geometry={nodes.Mesh_0487_36.geometry} material={materials['Material_0.043']} />
      <mesh geometry={nodes.Mesh_0487_37.geometry} material={materials['Material_1.022']} />
      <mesh geometry={nodes.Mesh_0487_38.geometry} material={materials['Material_0.044']} />
      <mesh geometry={nodes.Mesh_0487_39.geometry} material={materials['Material_0.045']} />
      <mesh geometry={nodes.Mesh_0487_40.geometry} material={materials['Material_0.046']} />
      <mesh geometry={nodes.Mesh_0487_41.geometry} material={materials['Material_1.023']} />
      <mesh geometry={nodes.Mesh_0487_42.geometry} material={materials['Material_0.047']} />
      <mesh geometry={nodes.Mesh_0487_43.geometry} material={materials['Material_0.051']} />
      <mesh geometry={nodes.Mesh_0487_44.geometry} material={materials['Material_1.025']} />
      <mesh geometry={nodes.Mesh_0487_45.geometry} material={materials['Material_0.053']} />
      <mesh geometry={nodes.Mesh_0487_46.geometry} material={materials['Material_1.027']} />
      <mesh geometry={nodes.Mesh_0487_47.geometry} material={materials['Material_0.054']} />
      <mesh geometry={nodes.Mesh_0487_48.geometry} material={materials['Material_0.056']} />
      <mesh geometry={nodes.Mesh_0487_49.geometry} material={materials['Material_1.028']} />
      <mesh geometry={nodes.Mesh_0487_50.geometry} material={materials['Material_0.057']} />
      <mesh geometry={nodes.Mesh_0487_51.geometry} material={materials['Material_0.060']} />
      <mesh geometry={nodes.Mesh_0487_52.geometry} material={materials['Material_0.064']} />
      <mesh geometry={nodes.Mesh_0487_53.geometry} material={materials['Material_1.031']} />
      <mesh geometry={nodes.Mesh_0487_54.geometry} material={materials['Material_0.065']} />
      <mesh geometry={nodes.Mesh_0487_55.geometry} material={materials['Material_1.032']} />
      <mesh geometry={nodes.Mesh_0487_56.geometry} material={materials['Material_0.066']} />
      <mesh geometry={nodes.Mesh_0487_57.geometry} material={materials['Material_1.033']} />
      <mesh geometry={nodes.Mesh_0487_58.geometry} material={materials['Material_0.067']} />
      <mesh geometry={nodes.Mesh_0487_59.geometry} material={materials['Material_1.034']} />
      <mesh geometry={nodes.Mesh_0487_60.geometry} material={materials['Material_0.068']} />
      <mesh geometry={nodes.Mesh_0487_61.geometry} material={materials['Material_1.035']} />
      <mesh geometry={nodes.Mesh_0487_62.geometry} material={materials['Material_0.069']} />
      <mesh geometry={nodes.Mesh_0487_63.geometry} material={materials['Material_1.036']} />
      <mesh geometry={nodes.Mesh_0487_64.geometry} material={materials['Material_0.070']} />
      <mesh geometry={nodes.Mesh_0487_65.geometry} material={materials['Material_1.037']} />
      <mesh geometry={nodes.Mesh_0487_66.geometry} material={materials['Material_0.071']} />
      <mesh geometry={nodes.Mesh_0487_67.geometry} material={materials['Material_1.038']} />
      <mesh geometry={nodes.Mesh_0487_68.geometry} material={materials['Material_0.072']} />
      <mesh geometry={nodes.Mesh_0487_69.geometry} material={materials['Material_1.039']} />
      <mesh geometry={nodes.Mesh_0487_70.geometry} material={materials['Material_0.073']} />
      <mesh geometry={nodes.Mesh_0487_71.geometry} material={materials['Material_1.040']} />
      <mesh geometry={nodes.Mesh_0487_72.geometry} material={materials['Material_0.074']} />
      <mesh geometry={nodes.Mesh_0487_73.geometry} material={materials['Material_1.041']} />
      <mesh geometry={nodes.Mesh_0487_74.geometry} material={materials['Material_0.075']} />
      <mesh geometry={nodes.Mesh_0487_75.geometry} material={materials['Material_1.042']} />
      <mesh geometry={nodes.Mesh_0487_76.geometry} material={materials['Material_0.076']} />
      <mesh geometry={nodes.Mesh_0487_77.geometry} material={materials['Material_1.043']} />
      <mesh geometry={nodes.Mesh_0487_78.geometry} material={materials['Material_0.077']} />
      <mesh geometry={nodes.Mesh_0487_79.geometry} material={materials['Material_1.044']} />
      <mesh geometry={nodes.Mesh_0487_80.geometry} material={materials['Material_0.078']} />
      <mesh geometry={nodes.Mesh_0487_81.geometry} material={materials['Material_1.045']} />
      <mesh geometry={nodes.Mesh_0487_82.geometry} material={materials['Material_0.079']} />
      <mesh geometry={nodes.Mesh_0487_83.geometry} material={materials['Material_1.046']} />
      <mesh geometry={nodes.Mesh_0487_84.geometry} material={materials['Material_0.080']} />
      <mesh geometry={nodes.Mesh_0487_85.geometry} material={materials['Material_1.047']} />
      <mesh geometry={nodes.Mesh_0487_86.geometry} material={materials['Material_0.081']} />
      <mesh geometry={nodes.Mesh_0487_87.geometry} material={materials['Material_1.048']} />
      <mesh geometry={nodes.Mesh_0487_88.geometry} material={materials['Material_0.082']} />
      <mesh geometry={nodes.Mesh_0487_89.geometry} material={materials['Material_1.049']} />
      <mesh geometry={nodes.Mesh_0487_90.geometry} material={materials['Material_0.083']} />
      <mesh geometry={nodes.Mesh_0487_91.geometry} material={materials['Material_1.050']} />
      <mesh geometry={nodes.Mesh_0487_92.geometry} material={materials['Material_0.085']} />
      <mesh geometry={nodes.Mesh_0487_93.geometry} material={materials['Material_1.052']} />
      <mesh geometry={nodes.Mesh_0487_94.geometry} material={materials['Material_0.086']} />
      <mesh geometry={nodes.Mesh_0487_95.geometry} material={materials['Material_1.053']} />
      <mesh geometry={nodes.Mesh_0487_96.geometry} material={materials['Material_0.087']} />
      <mesh geometry={nodes.Mesh_0487_97.geometry} material={materials['Material_0.088']} />
      <mesh geometry={nodes.Mesh_0487_98.geometry} material={materials['Material_1.055']} />
      <mesh geometry={nodes.Mesh_0487_99.geometry} material={materials['Material_0.092']} />
      <mesh geometry={nodes.Mesh_0487_100.geometry} material={materials['Material_0.093']} />
      <mesh geometry={nodes.Mesh_0487_101.geometry} material={materials['Material_0.094']} />
      <mesh geometry={nodes.Mesh_0487_102.geometry} material={materials['Material_0.095']} />
      <mesh geometry={nodes.Mesh_0487_103.geometry} material={materials['Material_0.096']} />
      <mesh geometry={nodes.Mesh_0487_104.geometry} material={materials['Material_0.098']} />
      <mesh geometry={nodes.Mesh_0487_105.geometry} material={materials['Material_0.099']} />
      <mesh geometry={nodes.Mesh_0487_106.geometry} material={materials['Material_0.100']} />
      <mesh geometry={nodes.Mesh_0487_107.geometry} material={materials['Material_1.058']} />
      <mesh geometry={nodes.Mesh_0487_108.geometry} material={materials['Material_0.101']} />
      <mesh geometry={nodes.Mesh_0487_109.geometry} material={materials['Material_1.059']} />
      <mesh geometry={nodes.Mesh_0487_110.geometry} material={materials['Material_0.102']} />
      <mesh geometry={nodes.Mesh_0487_111.geometry} material={materials['Material_1.060']} />
      <mesh geometry={nodes.Mesh_0487_112.geometry} material={materials['Material_0.103']} />
      <mesh geometry={nodes.Mesh_0487_113.geometry} material={materials['Material_1.061']} />
      <mesh geometry={nodes.Mesh_0487_114.geometry} material={materials['Material_0.104']} />
      <mesh geometry={nodes.Mesh_0487_115.geometry} material={materials['Material_1.062']} />
      <mesh geometry={nodes.Mesh_0487_116.geometry} material={materials['Material_0.105']} />
      <mesh geometry={nodes.Mesh_0487_117.geometry} material={materials['Material_1.063']} />
      <mesh geometry={nodes.Mesh_0487_118.geometry} material={materials['Material_0.106']} />
      <mesh geometry={nodes.Mesh_0487_119.geometry} material={materials['Material_1.064']} />
      <mesh geometry={nodes.Mesh_0487_120.geometry} material={materials['Material_0.107']} />
      <mesh geometry={nodes.Mesh_0487_121.geometry} material={materials['Material_1.065']} />
      <mesh geometry={nodes.Mesh_0487_122.geometry} material={materials['Material_0.108']} />
      <mesh geometry={nodes.Mesh_0487_123.geometry} material={materials['Material_1.066']} />
      <mesh geometry={nodes.Mesh_0487_124.geometry} material={materials['Material_0.109']} />
      <mesh geometry={nodes.Mesh_0487_125.geometry} material={materials['Material_1.067']} />
      <mesh geometry={nodes.Mesh_0487_126.geometry} material={materials['Material_0.110']} />
      <mesh geometry={nodes.Mesh_0487_127.geometry} material={materials['Material_1.068']} />
      <mesh geometry={nodes.Mesh_0487_128.geometry} material={materials['Material_0.111']} />
      <mesh geometry={nodes.Mesh_0487_129.geometry} material={materials['Material_1.069']} />
      <mesh geometry={nodes.Mesh_0487_130.geometry} material={materials['Material_0.112']} />
      <mesh geometry={nodes.Mesh_0487_131.geometry} material={materials['Material_0.113']} />
      <mesh geometry={nodes.Mesh_0487_132.geometry} material={materials['Material_1.070']} />
      <mesh geometry={nodes.Mesh_0487_133.geometry} material={materials['Material_0.114']} />
      <mesh geometry={nodes.Mesh_0487_134.geometry} material={materials['Material_0.115']} />
      <mesh geometry={nodes.Mesh_0487_135.geometry} material={materials['Material_1.071']} />
      <mesh geometry={nodes.Mesh_0487_136.geometry} material={materials['Material_0.116']} />
      <mesh geometry={nodes.Mesh_0487_137.geometry} material={materials['Material_0.117']} />
      <mesh geometry={nodes.Mesh_0487_138.geometry} material={materials['Material_1.072']} />
      <mesh geometry={nodes.Mesh_0487_139.geometry} material={materials['Material_0.118']} />
      <mesh geometry={nodes.Mesh_0487_140.geometry} material={materials['Material_0.119']} />
      <mesh geometry={nodes.Mesh_0487_141.geometry} material={materials['Material_1.073']} />
      <mesh geometry={nodes.Mesh_0487_142.geometry} material={materials['Material_0.120']} />
      <mesh geometry={nodes.Mesh_0487_143.geometry} material={materials['Material_0.121']} />
      <mesh geometry={nodes.Mesh_0487_144.geometry} material={materials['Material_0.122']} />
      <mesh geometry={nodes.Mesh_0487_145.geometry} material={materials['Material_1.074']} />
      <mesh geometry={nodes.Mesh_0487_146.geometry} material={materials['Material_0.123']} />
      <mesh geometry={nodes.Mesh_0487_147.geometry} material={materials['Material_1.075']} />
      <mesh geometry={nodes.Mesh_0487_148.geometry} material={materials['Material_0.124']} />
      <mesh geometry={nodes.Mesh_0487_149.geometry} material={materials['Material_1.076']} />
      <mesh geometry={nodes.Mesh_0487_150.geometry} material={materials['Material_0.125']} />
      <mesh geometry={nodes.Mesh_0487_151.geometry} material={materials['Material_1.077']} />
      <mesh geometry={nodes.Mesh_0487_152.geometry} material={materials['Material_0.126']} />
      <mesh geometry={nodes.Mesh_0487_153.geometry} material={materials['Material_0.127']} />
      <mesh geometry={nodes.Mesh_0487_154.geometry} material={materials['Material_1.078']} />
      <mesh geometry={nodes.Mesh_0487_155.geometry} material={materials['Material_0.128']} />
      <mesh geometry={nodes.Mesh_0487_156.geometry} material={materials['Material_1.079']} />
      <mesh geometry={nodes.Mesh_0487_157.geometry} material={materials['Material_0.133']} />
      <mesh geometry={nodes.Mesh_0487_158.geometry} material={materials['Material_1.084']} />
      <mesh geometry={nodes.Mesh_0487_159.geometry} material={materials['Material_0.134']} />
      <mesh geometry={nodes.Mesh_0487_160.geometry} material={materials['Material_0.135']} />
      <mesh geometry={nodes.Mesh_0487_161.geometry} material={materials['Material_1.085']} />
      <mesh geometry={nodes.Mesh_0487_162.geometry} material={materials['Material_0.136']} />
      <mesh geometry={nodes.Mesh_0487_163.geometry} material={materials['Material_1.086']} />
      <mesh geometry={nodes.Mesh_0487_164.geometry} material={materials['Material_0.138']} />
      <mesh geometry={nodes.Mesh_0487_165.geometry} material={materials['Material_1.088']} />
      <mesh geometry={nodes.Mesh_0487_166.geometry} material={materials['Material_0.140']} />
      <mesh geometry={nodes.Mesh_0487_167.geometry} material={materials['Material_1.090']} />
      <mesh geometry={nodes.Mesh_0487_168.geometry} material={materials['Material_0.141']} />
      <mesh geometry={nodes.Mesh_0487_169.geometry} material={materials['Material_1.091']} />
      <mesh geometry={nodes.Mesh_0487_170.geometry} material={materials['Material_0.142']} />
      <mesh geometry={nodes.Mesh_0487_171.geometry} material={materials['Material_1.092']} />
      <mesh geometry={nodes.Mesh_0487_172.geometry} material={materials['Material_0.143']} />
      <mesh geometry={nodes.Mesh_0487_173.geometry} material={materials['Material_1.093']} />
      <mesh geometry={nodes.Mesh_0487_174.geometry} material={materials['Material_0.144']} />
      <mesh geometry={nodes.Mesh_0487_175.geometry} material={materials['Material_1.094']} />
      <mesh geometry={nodes.Mesh_0487_176.geometry} material={materials['Material_0.145']} />
      <mesh geometry={nodes.Mesh_0487_177.geometry} material={materials['Material_0.146']} />
      <mesh geometry={nodes.Mesh_0487_178.geometry} material={materials['Material_0.147']} />
      <mesh geometry={nodes.Mesh_0487_179.geometry} material={materials['Material_1.095']} />
      <mesh geometry={nodes.Mesh_0487_180.geometry} material={materials['Material_0.148']} />
      <mesh geometry={nodes.Mesh_0487_181.geometry} material={materials['Material_1.096']} />
      <mesh geometry={nodes.Mesh_0487_182.geometry} material={materials['Material_0.149']} />
      <mesh geometry={nodes.Mesh_0487_183.geometry} material={materials['Material_0.150']} />
      <mesh geometry={nodes.Mesh_0487_184.geometry} material={materials['Material_1.097']} />
      <mesh geometry={nodes.Mesh_0487_185.geometry} material={materials['Material_0.151']} />
      <mesh geometry={nodes.Mesh_0487_186.geometry} material={materials['Material_1.098']} />
      <mesh geometry={nodes.Mesh_0487_187.geometry} material={materials['Material_0.152']} />
      <mesh geometry={nodes.Mesh_0487_188.geometry} material={materials['Material_1.099']} />
      <mesh geometry={nodes.Mesh_0487_189.geometry} material={materials['Material_0.153']} />
      <mesh geometry={nodes.Mesh_0487_190.geometry} material={materials['Material_1.100']} />
      <mesh geometry={nodes.Mesh_0487_191.geometry} material={materials['Material_0.154']} />
      <mesh geometry={nodes.Mesh_0487_192.geometry} material={materials['Material_1.101']} />
      <mesh geometry={nodes.Mesh_0487_193.geometry} material={materials['Material_0.155']} />
      <mesh geometry={nodes.Mesh_0487_194.geometry} material={materials['Material_1.102']} />
      <mesh geometry={nodes.Mesh_0487_195.geometry} material={materials['Material_0.156']} />
      <mesh geometry={nodes.Mesh_0487_196.geometry} material={materials['Material_1.103']} />
      <mesh geometry={nodes.Mesh_0487_197.geometry} material={materials['Material_0.157']} />
      <mesh geometry={nodes.Mesh_0487_198.geometry} material={materials['Material_0.158']} />
      <mesh geometry={nodes.Mesh_0487_199.geometry} material={materials['Material_1.104']} />
      <mesh geometry={nodes.Mesh_0487_200.geometry} material={materials['Material_0.159']} />
      <mesh geometry={nodes.Mesh_0487_201.geometry} material={materials['Material_1.105']} />
      <mesh geometry={nodes.Mesh_0487_202.geometry} material={materials['Material_0.160']} />
      <mesh geometry={nodes.Mesh_0487_203.geometry} material={materials['Material_1.106']} />
      <mesh geometry={nodes.Mesh_0487_204.geometry} material={materials['Material_0.161']} />
      <mesh geometry={nodes.Mesh_0487_205.geometry} material={materials['Material_0.162']} />
      <mesh geometry={nodes.Mesh_0487_206.geometry} material={materials['Material_0.163']} />
      <mesh geometry={nodes.Mesh_0487_207.geometry} material={materials['Material_0.164']} />
      <mesh geometry={nodes.Mesh_0487_208.geometry} material={materials['Material_0.165']} />
      <mesh geometry={nodes.Mesh_0487_209.geometry} material={materials['Material_0.166']} />
      <mesh geometry={nodes.Mesh_0487_210.geometry} material={materials['Material_0.167']} />
      <mesh geometry={nodes.Mesh_0487_211.geometry} material={materials['Material_0.168']} />
      <mesh geometry={nodes.Mesh_0487_212.geometry} material={materials['Material_0.169']} />
      <mesh geometry={nodes.Mesh_0487_213.geometry} material={materials['Material_0.170']} />
      <mesh geometry={nodes.Mesh_0487_214.geometry} material={materials['Material_0.171']} />
      <mesh geometry={nodes.Mesh_0487_215.geometry} material={materials['Material_1.107']} />
      <mesh geometry={nodes.Mesh_0487_216.geometry} material={materials['Material_0.172']} />
      <mesh geometry={nodes.Mesh_0487_217.geometry} material={materials['Material_1.108']} />
      <mesh geometry={nodes.Mesh_0487_218.geometry} material={materials['Material_0.173']} />
      <mesh geometry={nodes.Mesh_0487_219.geometry} material={materials['Material_0.174']} />
      <mesh geometry={nodes.Mesh_0487_220.geometry} material={materials['Material_0.175']} />
      <mesh geometry={nodes.Mesh_0487_221.geometry} material={materials['Material_1.109']} />
      <mesh geometry={nodes.Mesh_0487_222.geometry} material={materials['Material_0.176']} />
      <mesh geometry={nodes.Mesh_0487_223.geometry} material={materials['Material_1.110']} />
      <mesh geometry={nodes.Mesh_0487_224.geometry} material={materials['Material_0.177']} />
      <mesh geometry={nodes.Mesh_0487_225.geometry} material={materials['Material_1.111']} />
      <mesh geometry={nodes.Mesh_0487_226.geometry} material={materials['Material_0.178']} />
      <mesh geometry={nodes.Mesh_0487_227.geometry} material={materials['Material_1.112']} />
      <mesh geometry={nodes.Mesh_0487_228.geometry} material={materials['Material_0.179']} />
      <mesh geometry={nodes.Mesh_0487_229.geometry} material={materials['Material_0.180']} />
      <mesh geometry={nodes.Mesh_0487_230.geometry} material={materials['Material_0.181']} />
      <mesh geometry={nodes.Mesh_0487_231.geometry} material={materials['Material_0.182']} />
      <mesh geometry={nodes.Mesh_0487_232.geometry} material={materials['Material_0.183']} />
      <mesh geometry={nodes.Mesh_0487_233.geometry} material={materials['Material_0.184']} />
      <mesh geometry={nodes.Mesh_0487_234.geometry} material={materials['Material_1.113']} />
      <mesh geometry={nodes.Mesh_0487_235.geometry} material={materials['Material_0.185']} />
      <mesh geometry={nodes.Mesh_0487_236.geometry} material={materials['Material_0.198']} />
      <mesh geometry={nodes.Mesh_0487_237.geometry} material={materials['Material_0.199']} />
      <mesh geometry={nodes.Mesh_0487_238.geometry} material={materials['Material_1.121']} />
      <mesh geometry={nodes.Mesh_0487_239.geometry} material={materials['Material_0.200']} />
      <mesh geometry={nodes.Mesh_0487_240.geometry} material={materials['Material_1.122']} />
      <mesh geometry={nodes.Mesh_0487_241.geometry} material={materials['Material_0.201']} />
      <mesh geometry={nodes.Mesh_0487_242.geometry} material={materials['Material_1.123']} />
      <mesh geometry={nodes.Mesh_0487_243.geometry} material={materials['Material_0.202']} />
      <mesh geometry={nodes.Mesh_0487_244.geometry} material={materials['Material_1.124']} />
      <mesh geometry={nodes.Mesh_0487_245.geometry} material={materials['Material_0.203']} />
      <mesh geometry={nodes.Mesh_0487_246.geometry} material={materials['Material_1.125']} />
      <mesh geometry={nodes.Mesh_0487_247.geometry} material={materials['Material_0.204']} />
      <mesh geometry={nodes.Mesh_0487_248.geometry} material={materials['Material_1.126']} />
      <mesh geometry={nodes.Mesh_0487_249.geometry} material={materials['Material_0.205']} />
      <mesh geometry={nodes.Mesh_0487_250.geometry} material={materials['Material_1.127']} />
      <mesh geometry={nodes.Mesh_0487_251.geometry} material={materials['Material_0.206']} />
      <mesh geometry={nodes.Mesh_0487_252.geometry} material={materials['Material_0.207']} />
      <mesh geometry={nodes.Mesh_0487_253.geometry} material={materials['Material_0.208']} />
      <mesh geometry={nodes.Mesh_0487_254.geometry} material={materials['Material_1.128']} />
      <mesh geometry={nodes.Mesh_0487_255.geometry} material={materials['Material_0.209']} />
      <mesh geometry={nodes.Mesh_0487_256.geometry} material={materials['Material_0.210']} />
      <mesh geometry={nodes.Mesh_0487_257.geometry} material={materials['Material_0.211']} />
      <mesh geometry={nodes.Mesh_0487_258.geometry} material={materials['Material_0.212']} />
      <mesh geometry={nodes.Mesh_0487_259.geometry} material={materials['Material_0.213']} />
      <mesh geometry={nodes.Mesh_0487_260.geometry} material={materials['Material_1.129']} />
      <mesh geometry={nodes.Mesh_0487_261.geometry} material={materials['Material_0.214']} />
      <mesh geometry={nodes.Mesh_0487_262.geometry} material={materials['Material_0.216']} />
      <mesh geometry={nodes.Mesh_0487_263.geometry} material={materials['Material_0.220']} />
      <mesh geometry={nodes.Mesh_0487_264.geometry} material={materials['Material_0.221']} />
      <mesh geometry={nodes.Mesh_0487_265.geometry} material={materials['Material_0.222']} />
      <mesh geometry={nodes.Mesh_0487_266.geometry} material={materials['Material_0.223']} />
      <mesh geometry={nodes.Mesh_0487_267.geometry} material={materials['Material_1.133']} />
      <mesh geometry={nodes.Mesh_0487_268.geometry} material={materials['Material_0.226']} />
      <mesh geometry={nodes.Mesh_0487_269.geometry} material={materials['Material_0.227']} />
      <mesh geometry={nodes.Mesh_0487_270.geometry} material={materials['Material_0.228']} />
      <mesh geometry={nodes.Mesh_0487_271.geometry} material={materials['Material_0.236']} />
      <mesh geometry={nodes.Mesh_0487_272.geometry} material={materials['Material_0.237']} />
      <mesh geometry={nodes.Mesh_0487_273.geometry} material={materials['Material_0.238']} />
      <mesh geometry={nodes.Mesh_0487_274.geometry} material={materials['Material_0.239']} />
      <mesh geometry={nodes.Mesh_0487_275.geometry} material={materials['Material_0.240']} />
      <mesh geometry={nodes.Mesh_0487_276.geometry} material={materials['Material_0.241']} />
      <mesh geometry={nodes.Mesh_0487_277.geometry} material={materials['Material_0.242']} />
      <mesh geometry={nodes.Mesh_0487_278.geometry} material={materials['Material_0.248']} />
      <mesh geometry={nodes.Mesh_0487_279.geometry} material={materials['Material_0.254']} />
      <mesh geometry={nodes.Mesh_0487_280.geometry} material={materials['Material_0.256']} />
      <mesh geometry={nodes.Mesh_0487_281.geometry} material={materials['Material_0.257']} />
      <mesh geometry={nodes.Mesh_0487_282.geometry} material={materials['Material_0.258']} />
      <mesh geometry={nodes.Mesh_0487_283.geometry} material={materials['Material_1.135']} />
      <mesh geometry={nodes.Mesh_0487_284.geometry} material={materials['Material_0.259']} />
      <mesh geometry={nodes.Mesh_0487_285.geometry} material={materials['Material_1.136']} />
      <mesh geometry={nodes.Mesh_0487_286.geometry} material={materials['Material_0.260']} />
      <mesh geometry={nodes.Mesh_0487_287.geometry} material={materials['Material_0.266']} />
      <mesh geometry={nodes.Mesh_0487_288.geometry} material={materials['Material_0.269']} />
      <mesh geometry={nodes.Mesh_0487_289.geometry} material={materials['Material_1.143']} />
      <mesh geometry={nodes.Mesh_0487_290.geometry} material={materials['Material_0.270']} />
      <mesh geometry={nodes.Mesh_0487_291.geometry} material={materials['Material_0.271']} />
      <mesh geometry={nodes.Mesh_0487_292.geometry} material={materials['Material_1.144']} />
      <mesh geometry={nodes.Mesh_0487_293.geometry} material={materials['Material_0.272']} />
      <mesh geometry={nodes.Mesh_0487_294.geometry} material={materials['Material_1.145']} />
      <mesh geometry={nodes.Mesh_0487_295.geometry} material={materials['Material_0.273']} />
      <mesh geometry={nodes.Mesh_0487_296.geometry} material={materials['Material_1.146']} />
      <mesh geometry={nodes.Mesh_0487_297.geometry} material={materials['Material_0.274']} />
      <mesh geometry={nodes.Mesh_0487_298.geometry} material={materials['Material_1.147']} />
      <mesh geometry={nodes.Mesh_0487_299.geometry} material={materials['Material_0.275']} />
      <mesh geometry={nodes.Mesh_0487_300.geometry} material={materials['Material_1.148']} />
      <mesh geometry={nodes.Mesh_0487_301.geometry} material={materials['Material_0.276']} />
      <mesh geometry={nodes.Mesh_0487_302.geometry} material={materials['Material_1.149']} />
      <mesh geometry={nodes.Mesh_0487_303.geometry} material={materials['Material_0.277']} />
      <mesh geometry={nodes.Mesh_0487_304.geometry} material={materials['Material_1.150']} />
      <mesh geometry={nodes.Mesh_0487_305.geometry} material={materials['Material_0.278']} />
      <mesh geometry={nodes.Mesh_0487_306.geometry} material={materials['Material_1.151']} />
      <mesh geometry={nodes.Mesh_0487_307.geometry} material={materials['Material_0.279']} />
      <mesh geometry={nodes.Mesh_0487_308.geometry} material={materials['Material_1.152']} />
      <mesh geometry={nodes.Mesh_0487_309.geometry} material={materials['Material_0.280']} />
      <mesh geometry={nodes.Mesh_0487_310.geometry} material={materials['Material_1.153']} />
      <mesh geometry={nodes.Mesh_0487_311.geometry} material={materials['Material_0.281']} />
      <mesh geometry={nodes.Mesh_0487_312.geometry} material={materials['Material_1.154']} />
      <mesh geometry={nodes.Mesh_0487_313.geometry} material={materials['Material_0.282']} />
      <mesh geometry={nodes.Mesh_0487_314.geometry} material={materials['Material_1.155']} />
      <mesh geometry={nodes.Mesh_0487_315.geometry} material={materials['Material_0.283']} />
      <mesh geometry={nodes.Mesh_0487_316.geometry} material={materials['Material_1.156']} />
      <mesh geometry={nodes.Mesh_0487_317.geometry} material={materials['Material_0.284']} />
      <mesh geometry={nodes.Mesh_0487_318.geometry} material={materials['Material_1.157']} />
      <mesh geometry={nodes.Mesh_0487_319.geometry} material={materials['Material_0.301']} />
      <mesh geometry={nodes.Mesh_0487_320.geometry} material={materials['Material_1.166']} />
      <mesh geometry={nodes.Mesh_0487_321.geometry} material={materials['Material_0.302']} />
      <mesh geometry={nodes.Mesh_0487_322.geometry} material={materials['Material_0.305']} />
      <mesh geometry={nodes.Mesh_0487_323.geometry} material={materials['Material_1.169']} />
      <mesh geometry={nodes.Mesh_0487_324.geometry} material={materials['Material_0.306']} />
      <mesh geometry={nodes.Mesh_0487_325.geometry} material={materials['Material_1.170']} />
      <mesh geometry={nodes.Mesh_0487_326.geometry} material={materials['Material_0.307']} />
      <mesh geometry={nodes.Mesh_0487_327.geometry} material={materials['Material_1.171']} />
      <mesh geometry={nodes.Mesh_0487_328.geometry} material={materials['Material_0.308']} />
      <mesh geometry={nodes.Mesh_0487_329.geometry} material={materials['Material_0.322']} />
      <mesh geometry={nodes.Mesh_0487_330.geometry} material={materials['Material_0.323']} />
      <mesh geometry={nodes.Mesh_0487_331.geometry} material={materials['Material_0.324']} />
      <mesh geometry={nodes.Mesh_0487_332.geometry} material={materials['Material_0.325']} />
      <mesh geometry={nodes.Mesh_0487_333.geometry} material={materials['Material_0.326']} />
      <mesh geometry={nodes.Mesh_0487_334.geometry} material={materials['Material_0.327']} />
      <mesh geometry={nodes.Mesh_0487_335.geometry} material={materials['Material_0.328']} />
      <mesh geometry={nodes.Mesh_0487_336.geometry} material={materials['Material_0.329']} />
      <mesh geometry={nodes.Mesh_0487_337.geometry} material={materials['Material_0.330']} />
      <mesh geometry={nodes.Mesh_0487_338.geometry} material={materials['Material_0.332']} />
      <mesh geometry={nodes.Mesh_0487_339.geometry} material={materials['Material_0.333']} />
      <mesh geometry={nodes.Mesh_0487_340.geometry} material={materials['Material_0.334']} />
      <mesh geometry={nodes.Mesh_0487_341.geometry} material={materials['Material_0.335']} />
      <mesh geometry={nodes.Mesh_0487_342.geometry} material={materials['Material_0.336']} />
      <mesh geometry={nodes.Mesh_0487_343.geometry} material={materials['Material_1.176']} />
      <mesh geometry={nodes.Mesh_0487_344.geometry} material={materials['Material_0.337']} />
      <mesh geometry={nodes.Mesh_0487_345.geometry} material={materials['Material_1.177']} />
      <mesh geometry={nodes.Mesh_0487_346.geometry} material={materials['Material_0.338']} />
      <mesh geometry={nodes.Mesh_0487_347.geometry} material={materials['Material_1.178']} />
      <mesh geometry={nodes.Mesh_0487_348.geometry} material={materials['Material_0.339']} />
      <mesh geometry={nodes.Mesh_0487_349.geometry} material={materials['Material_1.179']} />
      <mesh geometry={nodes.Mesh_0487_350.geometry} material={materials['Material_0.340']} />
      <mesh geometry={nodes.Mesh_0487_351.geometry} material={materials['Material_0.341']} />
      <mesh geometry={nodes.Mesh_0487_352.geometry} material={materials['Material_1.180']} />
      <mesh geometry={nodes.Mesh_0487_353.geometry} material={materials['Material_0.342']} />
      <mesh geometry={nodes.Mesh_0487_354.geometry} material={materials['Material_1.181']} />
      <mesh geometry={nodes.Mesh_0487_355.geometry} material={materials['Material_0.343']} />
      <mesh geometry={nodes.Mesh_0487_356.geometry} material={materials['Material_1.182']} />
      <mesh geometry={nodes.Mesh_0487_357.geometry} material={materials['Material_0.344']} />
      <mesh geometry={nodes.Mesh_0487_358.geometry} material={materials['Material_1.183']} />
      <mesh geometry={nodes.Mesh_0487_359.geometry} material={materials['Material_0.345']} />
      <mesh geometry={nodes.Mesh_0487_360.geometry} material={materials['Material_1.184']} />
      <mesh geometry={nodes.Mesh_0487_361.geometry} material={materials['Material_0.346']} />
      <mesh geometry={nodes.Mesh_0487_362.geometry} material={materials['Material_1.185']} />
      <mesh geometry={nodes.Mesh_0487_363.geometry} material={materials['Material_0.347']} />
      <mesh geometry={nodes.Mesh_0487_364.geometry} material={materials['Material_0.348']} />
      <mesh geometry={nodes.Mesh_0487_365.geometry} material={materials['Material_1.186']} />
      <mesh geometry={nodes.Mesh_0487_366.geometry} material={materials['Material_0.349']} />
      <mesh geometry={nodes.Mesh_0487_367.geometry} material={materials['Material_1.187']} />
      <mesh geometry={nodes.Mesh_0487_368.geometry} material={materials['Material_0.350']} />
      <mesh geometry={nodes.Mesh_0487_369.geometry} material={materials['Material_0.351']} />
      <mesh geometry={nodes.Mesh_0487_370.geometry} material={materials['Material_1.188']} />
      <mesh geometry={nodes.Mesh_0487_371.geometry} material={materials['Material_0.352']} />
      <mesh geometry={nodes.Mesh_0487_372.geometry} material={materials['Material_0.353']} />
      <mesh geometry={nodes.Mesh_0487_373.geometry} material={materials['Material_0.354']} />
      <mesh geometry={nodes.Mesh_0487_374.geometry} material={materials['Material_1.189']} />
      <mesh geometry={nodes.Mesh_0487_375.geometry} material={materials['Material_0.355']} />
      <mesh geometry={nodes.Mesh_0487_376.geometry} material={materials['Material_0.358']} />
      <mesh geometry={nodes.Mesh_0487_377.geometry} material={materials['Material_1.191']} />
      <mesh geometry={nodes.Mesh_0487_378.geometry} material={materials['Material_0.359']} />
      <mesh geometry={nodes.Mesh_0487_379.geometry} material={materials['Material_1.192']} />
      <mesh geometry={nodes.Mesh_0487_380.geometry} material={materials['Material_0.360']} />
      <mesh geometry={nodes.Mesh_0487_381.geometry} material={materials['Material_1.193']} />
      <mesh geometry={nodes.Mesh_0487_382.geometry} material={materials['Material_0.361']} />
      <mesh geometry={nodes.Mesh_0487_383.geometry} material={materials['Material_1.194']} />
      <mesh geometry={nodes.Mesh_0487_384.geometry} material={materials['Material_0.364']} />
      <mesh geometry={nodes.Mesh_0487_385.geometry} material={materials['Material_0.365']} />
      <mesh geometry={nodes.Mesh_0487_386.geometry} material={materials['Material_1.195']} />
      <mesh geometry={nodes.Mesh_0487_387.geometry} material={materials['Material_0.366']} />
      <mesh geometry={nodes.Mesh_0487_388.geometry} material={materials['Material_0.367']} />
      <mesh geometry={nodes.Mesh_0487_389.geometry} material={materials['Material_1.196']} />
      <mesh geometry={nodes.Mesh_0487_390.geometry} material={materials['Material_0.368']} />
      <mesh geometry={nodes.Mesh_0487_391.geometry} material={materials['Material_0.369']} />
      <mesh geometry={nodes.Mesh_0487_392.geometry} material={materials['Material_1.197']} />
      <mesh geometry={nodes.Mesh_0487_393.geometry} material={materials['Material_0.370']} />
      <mesh geometry={nodes.Mesh_0487_394.geometry} material={materials['Material_1.198']} />
      <mesh geometry={nodes.Mesh_0487_395.geometry} material={materials['Material_0.371']} />
      <mesh geometry={nodes.Mesh_0487_396.geometry} material={materials['Material_1.199']} />
      <mesh geometry={nodes.Mesh_0487_397.geometry} material={materials['Material_0.372']} />
      <mesh geometry={nodes.Mesh_0487_398.geometry} material={materials['Material_0.373']} />
      <mesh geometry={nodes.Mesh_0487_399.geometry} material={materials['Material_1.200']} />
      <mesh geometry={nodes.Mesh_0487_400.geometry} material={materials['Material_0.375']} />
      <mesh geometry={nodes.Mesh_0487_401.geometry} material={materials['Material_0.376']} />
      <mesh geometry={nodes.Mesh_0487_402.geometry} material={materials['Material_1.202']} />
      <mesh geometry={nodes.Mesh_0487_403.geometry} material={materials['Material_0.377']} />
      <mesh geometry={nodes.Mesh_0487_404.geometry} material={materials['Material_0.378']} />
      <mesh geometry={nodes.Mesh_0487_405.geometry} material={materials['Material_1.203']} />
      <mesh geometry={nodes.Mesh_0487_406.geometry} material={materials['Material_0.379']} />
      <mesh geometry={nodes.Mesh_0487_407.geometry} material={materials['Material_1.204']} />
      <mesh geometry={nodes.Mesh_0487_408.geometry} material={materials['Material_0.380']} />
      <mesh geometry={nodes.Mesh_0487_409.geometry} material={materials['Material_1.205']} />
      <mesh geometry={nodes.Mesh_0487_410.geometry} material={materials['Material_0.381']} />
      <mesh geometry={nodes.Mesh_0487_411.geometry} material={materials['Material_0.382']} />
      <mesh geometry={nodes.Mesh_0487_412.geometry} material={materials['Material_1.206']} />
      <mesh geometry={nodes.Mesh_0487_413.geometry} material={materials['Material_0.383']} />
      <mesh geometry={nodes.Mesh_0487_414.geometry} material={materials['Material_0.386']} />
      <mesh geometry={nodes.Mesh_0487_415.geometry} material={materials['Material_1.208']} />
      <mesh geometry={nodes.Mesh_0487_416.geometry} material={materials['Material_0.387']} />
      <mesh geometry={nodes.Mesh_0487_417.geometry} material={materials['Material_0.388']} />
      <mesh geometry={nodes.Mesh_0487_418.geometry} material={materials['Material_1.210']} />
      <mesh geometry={nodes.Mesh_0487_419.geometry} material={materials['Material_0.389']} />
      <mesh geometry={nodes.Mesh_0487_420.geometry} material={materials['Material_0.392']} />
      <mesh geometry={nodes.Mesh_0487_421.geometry} material={materials['Material_0.393']} />
      <mesh geometry={nodes.Mesh_0487_422.geometry} material={materials['Material_0.394']} />
      <mesh geometry={nodes.Mesh_0487_423.geometry} material={materials['Material_0.395']} />
      <mesh geometry={nodes.Mesh_0487_424.geometry} material={materials['Material_0.396']} />
      <mesh geometry={nodes.Mesh_0487_425.geometry} material={materials['Material_0.397']} />
      <mesh geometry={nodes.Mesh_0487_426.geometry} material={materials['Material_0.398']} />
      <mesh geometry={nodes.Mesh_0487_427.geometry} material={materials['Material_0.399']} />
      <mesh geometry={nodes.Mesh_0487_428.geometry} material={materials['Material_0.400']} />
      <mesh geometry={nodes.Mesh_0487_429.geometry} material={materials['Material_0.401']} />
      <mesh geometry={nodes.Mesh_0487_430.geometry} material={materials['Material_0.402']} />
      <mesh geometry={nodes.Mesh_0487_431.geometry} material={materials['Material_0.403']} />
      <mesh geometry={nodes.Mesh_0487_432.geometry} material={materials['Material_0.404']} />
      <mesh geometry={nodes.Mesh_0487_433.geometry} material={materials['Material_0.405']} />
      <mesh geometry={nodes.Mesh_0487_434.geometry} material={materials['Material_0.406']} />
      <mesh geometry={nodes.Mesh_0487_435.geometry} material={materials['Material_0.407']} />
      <mesh geometry={nodes.Mesh_0487_436.geometry} material={materials['Material_0.409']} />
      <mesh geometry={nodes.Mesh_0487_437.geometry} material={materials['Material_0.412']} />
      <mesh geometry={nodes.Mesh_0487_438.geometry} material={materials['Material_0.414']} />
      <mesh geometry={nodes.Mesh_0487_439.geometry} material={materials['Material_0.418']} />
      <mesh geometry={nodes.Mesh_0487_440.geometry} material={materials['Material_0.419']} />
      <mesh geometry={nodes.Mesh_0487_441.geometry} material={materials['Material_0.420']} />
      <mesh geometry={nodes.Mesh_0487_442.geometry} material={materials['Material_0.421']} />
      <mesh geometry={nodes.Mesh_0487_443.geometry} material={materials['Material_0.422']} />
      <mesh geometry={nodes.Mesh_0487_444.geometry} material={materials['Material_0.423']} />
      <mesh geometry={nodes.Mesh_0487_445.geometry} material={materials['Material_0.424']} />
      <mesh geometry={nodes.Mesh_0487_446.geometry} material={materials['Material_0.425']} />
      <mesh geometry={nodes.Mesh_0487_447.geometry} material={materials['Material_0.426']} />
      <mesh geometry={nodes.Mesh_0487_448.geometry} material={materials['Material_0.427']} />
      <mesh geometry={nodes.Mesh_0487_449.geometry} material={materials['Material_0.428']} />
      <mesh geometry={nodes.Mesh_0487_450.geometry} material={materials['Material_0.429']} />
      <mesh geometry={nodes.Mesh_0487_451.geometry} material={materials['Material_0.434']} />
      <mesh geometry={nodes.Mesh_0487_452.geometry} material={materials['Material_0.467']} />
      <mesh geometry={nodes.Mesh_0487_453.geometry} material={materials['Material_1.226']} />
      <mesh geometry={nodes.Mesh_0487_454.geometry} material={materials['Material_0.468']} />
      <mesh geometry={nodes.Mesh_0487_455.geometry} material={materials['Material_1.227']} />
      <mesh geometry={nodes.Mesh_0487_456.geometry} material={materials['Material_0.469']} />
      <mesh geometry={nodes.Mesh_0487_457.geometry} material={materials['Material_0.470']} />
      <mesh geometry={nodes.Mesh_0487_458.geometry} material={materials['Material_0.473']} />
      <mesh geometry={nodes.Mesh_0487_459.geometry} material={materials['Material_1.228']} />
      <mesh geometry={nodes.Mesh_0487_460.geometry} material={materials['Material_0.474']} />
      <mesh geometry={nodes.Mesh_0487_461.geometry} material={materials['Material_1.229']} />
      <mesh geometry={nodes.Mesh_0487_462.geometry} material={materials['Material_0.475']} />
      <mesh geometry={nodes.Mesh_0487_463.geometry} material={materials['Material_1.230']} />
      <mesh geometry={nodes.Mesh_0487_464.geometry} material={materials['Material_0.476']} />
      <mesh geometry={nodes.Mesh_0487_465.geometry} material={materials['Material_1.231']} />
      <mesh geometry={nodes.Mesh_0487_466.geometry} material={materials['Material_0.477']} />
      <mesh geometry={nodes.Mesh_0487_467.geometry} material={materials['Material_0.478']} />
      <mesh geometry={nodes.Mesh_0487_468.geometry} material={materials['Material_1.232']} />
      <mesh geometry={nodes.Mesh_0487_469.geometry} material={materials['Material_0.481']} />
      <mesh geometry={nodes.Mesh_0487_470.geometry} material={materials['Material_0.482']} />
      <mesh geometry={nodes.Mesh_0487_471.geometry} material={materials['Material_0.484']} />
      <mesh geometry={nodes.Mesh_0487_472.geometry} material={materials['Material_0.485']} />
      <mesh geometry={nodes.Mesh_0487_473.geometry} material={materials['Material_0.486']} />
    </group>
  )
}

useGLTF.preload('/../uclan_lg-transformed.glb')
